### PR TITLE
fix(package): remove low vulnerability by upgrading dependencies BREAKING CHANGE

### PR DESCRIPTION
**Pull request by bankyadam**
More info: https://nodesecurity.io/advisories/577

### CODE REVIEW

**Comment by bankyadam** [comment]
As `sinon` had been updated to 5.x from 1.x, this could be maybe a BREAKING CHANGE?

**Comment by sonicoder86** [comment]
I would consider it breaking as it is not a dev dependency

**Review by sonicoder86 — CHANGES_REQUESTED** [review]
Please add BREAKING CHANGES to the commit

**Comment by bankyadam** [comment]
@blacksonic I added a new commit and renamed the PR.

**Review by sonicoder86 — APPROVED** [review]

**Pull request merged**
